### ISSUE TITLE
Why do we have 2 versions of `jscolor` ?

### ISSUE THREAD

**Issue by baseplate-admin** [fabiocaccamo/django-colorfield#121]
Hi,

It seems that you are bundling 2 versions of `jscolor`. 

https://github.com/fabiocaccamo/django-colorfield/blob/b17e7fbbf03bf6f3a4f58f993e1b6ba7199743e8/colorfield/widgets.py#L10-L19

Is there any particular reason for this?

**Comment by fabiocaccamo** [comment]
@baseplate-admin if `DEBUG` is `True`, the non minified `jscolor` version is used for simplifying debugging.

**Comment by baseplate-admin** [comment]
> if DEBUG is True, the non minified jscolor version is used for simplifying debugging.

Does minified JS change debugging that much?

Almost all the 1st/3rd party django js are using the minified codes
