### ISSUE TITLE
Django 4.2 Error from PIL (Pillow)

### ISSUE THREAD

**Issue by FloCondignum** [fabiocaccamo/django-colorfield#133]
**ImportError in Django 4.2**
Hi, i am currently trying to update my Django project from 4.1 to 4.2 but I get an ImportError suddenly. 

**Error:  ImportError: cannot import name '_imaging' from 'PIL' (/var/task/PIL/__init__.py)**

I have checked this error. Usually, a new installation of Pillow should fix the problem, but I still cannot get past this. 
Is something similiar known? I know that 4.2 is not officially supported yet, but may be this is helpful for others as well. 

Cheers,

Flo

<a href="https://dashboard.polar.sh/fabiocaccamo/django-colorfield/issues/133">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://dashboard.polar.sh/api/github/fabiocaccamo/django-colorfield/issues/133/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://dashboard.polar.sh/api/github/fabiocaccamo/django-colorfield/issues/133/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@FloCondignum thanks for reporting this. 

That's strange, I'm using this package on some project running on `Django 4.2` and I have not any issue.

**Comment by FloCondignum** [comment]
it was my bad. sorry. 
i had 3.9 on one aws service and 3.10 on another. This mismatch created this error. sorry for the inconvenience.
