### ISSUE TITLE
Crash when using `image_field` with RGB/RGBA formats

### ISSUE THREAD

**Issue by browniebroke** [fabiocaccamo/django-colorfield#153]
**Python version**
n/a

**Django version**
n/a

**Package version**
0.10.0

**Current behavior (bug description)**
The [recently added feature](https://github.com/fabiocaccamo/django-colorfield/pull/151) for RGB & RGBA doesn't work with the `image_field` feature. Issue noted https://github.com/fabiocaccamo/django-colorfield/issues/151#issuecomment-1706132604

> I realized just now that RGB and RGBA formats raise an error when the `image_field` option is used: https://github.com/fabiocaccamo/django-colorfield#image_field
> 
> This happens because the color returned by `get_image_background_color` (https://github.com/fabiocaccamo/django-colorfield/blob/main/colorfield/utils.py#L4) is always in HEX / HEXA format.

**Expected behavior**
RGB/RGBA format should work with `image_field`.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/django-colorfield/issues/153">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/django-colorfield/issues/153/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/django-colorfield/issues/153/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
Thank you for the PR, fix available in `0.10.1` version.
