### ISSUE TITLE
choose from subset of colors?

### ISSUE THREAD

**Issue by vsoch** [fabiocaccamo/django-colorfield#19]
Does the module allow for selection from a core set of colors? (versus the whole gamut!)

**Comment by fabiocaccamo** [comment]
Hi @vsoch, 
no actually it doesn't, I think that the 'choices' support would be a nice feature, feel free to submit a PR.

**Comment by gamesbook** [comment]
I'd support this idea; there are many times that clients need to ensure consistency by only choosing from a subset of options.

**Comment by fabiocaccamo** [comment]
@vsoch  `django-colorfield==0.4.0` (thanks to the great work of @rcatajar) now supports `choices=YOUR_COLOR_CHOICES` option for doing exactly what you need.
