### ISSUE TITLE
Color picker widget does not work in model forms

### ISSUE THREAD

**Issue by moonburnt** [fabiocaccamo/django-colorfield#202]
**Python version**
3.12

**Django version**
4.2.7

**Package version**
0.11.0

**Current behavior (bug description)**
Color picker widget does not seem to work for model forms?

Specified it like that:

```python
from colorfield.widgets import ColorWidget
from django import forms

class MyModelForm(forms.ModelForm):
    class Meta:
       model = MyModel
       fields = [
           "background_color",
       ]
       widgets = {
           "background_color": ColorWidget,
       }
 ```
 
And this is what I get in the form view:
![image](https://github.com/user-attachments/assets/52114d1f-5e74-4b23-a6e8-0b6cf07bc0c1)

**Expected behavior**
"Background Color" field should have a color picker widget instead of a text input.

**Additional information**
I'm using django-oscar for the admin interface, on which this occurs. So maybe its not a bug in this library, but a conflict with django-oscar's templates?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/django-colorfield/issues/202">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/django-colorfield/issues/202/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/django-colorfield/issues/202/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@moonburnt I'm pretty sure it's a conflict, are there errors in the browser's console?

**Comment by fabiocaccamo** [comment]
@moonburnt any feedback?

**Comment by moonburnt** [comment]
> @moonburnt I'm pretty sure it's a conflict, are there errors in the browser's console?

nope, no errors in the console

**Comment by fabiocaccamo** [comment]
Could you try without `django-oscar` please?
