### ISSUE TITLE
JsColor has a commercial license, whereas this repo advertises an MIT license.

### ISSUE THREAD

**Issue by austintrose** [fabiocaccamo/django-colorfield#33]
I recently started using `django-colorfield` in a commercial application. I assumed that this was OK, given the MIT license advertised here. However, on the [official jscolor](http://jscolor.com/download/) page they clearly describe their commercial license.

So, without purchasing a commercial license from `jscolor` is is inappropriate to use `django-colorfield` in any non-open-source software.

**Comment by jaredly** [comment]
oh great point. looks like when upgrading to version 2.0.4 their license changed; it was previously LGPL, and there was no commercial license.
This change happened long after I stopped using / actively maintaining this library, and I didn't notice :(

We should move over to [Spectrum](https://github.com/bgrins/spectrum) or [colorPicker](https://github.com/PitPik/colorPicker), both of which are MIT licensed

**Comment by fabiocaccamo** [comment]
I think that a good improvement would be to support multiple color-pickers libs to allow the users to choose the right one for their project via settings, in this way we can also continue to use jscolor for non-commercial projects.

**Comment by austintrose** [comment]
That's a nice idea! There's [`django-color-utils`](https://github.com/timchurch/django-color-utils) which does something similar, but appears to have been abandoned quite a while ago.

**Comment by mihalikv** [comment]
here you have closed PR for replacement to spectrum.

**Comment by politas** [comment]
JsColor's Licence page actually says 
>If you are creating an open source application under a license compatible with the GNU GPL license v3, feel free to use jscolor under the terms of GNU GPL license v3.

So there doesn't seem to be a problem here, as long as no one tries to use the jsColor part in a proprietary project.
