### ISSUE TITLE
Colorfield in Meta as Widget not working?

### ISSUE THREAD

**Issue by Asterrea** [fabiocaccamo/django-colorfield#34]
I'm not sure if this is happening to anyone else but the color widget won't show up in my form. Assuming that I have the correct code implementation as followed from Django Tutorials:

```
from django import forms
from .models import MyModel
from colorfield.fields import ColorWidget

class MyModelForm(forms.ModelForm):
    class Meta:
        model = MyModel
        fields =  ('myModel_id','agency_id', 'short_name', 'long_name',
                   'description', 'rtype', 'url')
        widgets = {
            'color' : forms.CharField(widget=ColorWidget),
            'text_color':forms.CharField(widget=ColorWidget)
        }
```

![image](https://user-images.githubusercontent.com/7810581/29266816-af3c7620-8118-11e7-8142-2a57bf0dc932.png)

Am I doing a wrong implementation?
Thanks in advance!

**Comment by sidneijp** [comment]
You must put `color`  and `text_color` on `fields` too.
