### ISSUE TITLE
Invalid color #FF0000

### ISSUE THREAD

**Issue by alexander-pastukhov** [fabiocaccamo/django-colorfield#36]
Hi,

I have a project that uses django-color and all went swimmingly, while I was using 0.1.10. Thanks for a very useful field! However, after I've upgraded to 0.1.14, it would never validate the color string, such as "#FF0000" I've used as default. I have solved the problem by rolling back to 0.1.10. I am not sure what kind of diagnostic I can provide for the issue.

Best regards,
Alexander

**Comment by fabiocaccamo** [comment]
I just released `0.2.0` version, could you check it please?
