### ISSUE TITLE
widget attrs

### ISSUE THREAD

**Issue by r-f-g** [fabiocaccamo/django-colorfield#43]
cannot pass widget attrs for modal at bootstrap4

`ColorWidget(attrs={'class': 'form-control colorfield_field jscolor {zIndex: 1080}'})`

**Comment by polrodoreda** [comment]
Same problem here. It will be a great update.

**Comment by fabiocaccamo** [comment]
I just released `0.2.0` version, could you check it please?

**Comment by N1K1TAS95** [comment]
Hi!
I stil have this issue.
My form is:
```
from colorfield.widgets import ColorWidget

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'fontawesome_icon', 'color']
        widgets = {'color': ColorWidget(attrs={'class': 'input'})}
```
and when rendered the resulting input classes are `form-control colorfield_field jscolor`. 

I have colorfield versione `0.7.0` and Django `4.0.4`

Thanks 😉.

**Comment by fabiocaccamo** [comment]
@N1K1TAS95 thank you for reporting this, if in the meantime you fix it, feel free to submit a PR.

**Comment by N1K1TAS95** [comment]
@fabiocaccamo I've added a PR.
I found that template `color.html` did not included `{{ class }}` from context while rendering.

**Comment by N1K1TAS95** [comment]
@fabiocaccamo 
I also think that `form-control` is for Bootstrap only. Maybe it's the case to remove this defalut class and let user decide it. But it maybe break someones code...

**Comment by fabiocaccamo** [comment]
@N1K1TAS95 thank you for the PR, you can upgrade to `0.7.1` version.
