### ISSUE TITLE
django.template.exceptions.TemplateDoesNotExist: colorfield/color.html

### ISSUE THREAD

**Issue by jeanluc243** [fabiocaccamo/django-colorfield#44]
the color.html is not found

**Comment by jeanluc243** [comment]
[ solution ] create in templates folder

`colorfield/color.html`

and in the color.html add this code

`<input type="text" name="{{ name }}" {% if value %}value="{{ value }}"{% endif %} id="{{ attrs.id }}"
class="colorfield_field jscolor {% if not is_required %}{required:false}{% endif %}"/>`

**Comment by fabiocaccamo** [comment]
Probably you forgot to add `colorfield` to `settings.INSTALLED_APPS`.

**Comment by rspeed** [comment]
I just had this occur because colorfield was somehow installed as an egg. There isn't a `zip_safe` setting in `setup.py`, so maybe that has something to do with it?
