### ISSUE TITLE
Repository ownership.

### ISSUE THREAD

**Issue by fabiocaccamo** [fabiocaccamo/django-colorfield#48]
@jaredly since you are no more active on this repository, could you transfer to me the ownership of this repo?

**Comment by jaredly** [comment]
Yup that sounds fine :)

**Comment by jaredly** [comment]
oh, looks like I can't transfer it to you while you have an active fork of it 🙃 I get the error "fabiocaccamo/django-colorfield exists"

**Comment by fabiocaccamo** [comment]
I just deleted the fork.

**Comment by jaredly** [comment]
Ok, I think you have to accept now, and then it's done! Thanks for taking over :)

**Comment by fabiocaccamo** [comment]
I accepted, thank you very much!
