### ISSUE TITLE
color picker screenshot

### ISSUE THREAD

**Issue by fabiocaccamo** [fabiocaccamo/django-colorfield#49]
![Schermata 2020-02-17 alle 18 14 55](https://user-images.githubusercontent.com/1035294/74674565-f33ace00-51b1-11ea-8669-4b952f2b8e56.png)

**Comment by rcatajar** [comment]
Screen new field look

![image](https://user-images.githubusercontent.com/7900305/104481539-3241f100-55c6-11eb-8fae-c4f1b4f30ca5.png)

**Comment by rcatajar** [comment]
Screen hexa
![image](https://user-images.githubusercontent.com/7900305/104481799-7e8d3100-55c6-11eb-8ab1-7d9a1ceb3040.png)

**Comment by rcatajar** [comment]
With palette
![image](https://user-images.githubusercontent.com/7900305/104482636-72ee3a00-55c7-11eb-942b-067f325fac1d.png)

**Comment by fabiocaccamo** [comment]
@rcatajar could you add the same top, left, bottom, right margins like in my first screenshot?

**Comment by rcatajar** [comment]
hex
![oie_aYuKJWstAmIG](https://user-images.githubusercontent.com/7900305/104512324-51ed0f80-55ee-11eb-9144-de03d922c2ce.png)


hexa
![oie_nfXHNXiMTvxq](https://user-images.githubusercontent.com/7900305/104512063-ec991e80-55ed-11eb-95b6-9174ac3f4f38.png)

Palette
![oie_GDxJi71N2qFX](https://user-images.githubusercontent.com/7900305/104512178-194d3600-55ee-11eb-8cba-91cca156da06.png)
