### ISSUE TITLE
TemplateDoesNotExist when viewing model in admin panel.

### ISSUE THREAD

**Issue by cclloyd** [fabiocaccamo/django-colorfield#50]
**Python version**
3.7.6

**Django version**
3.0.3

**Package version**
3.2.1

**Current behavior (bug description)**
When viewing model or trying to create a new model in admin panel (dev mode), I get the following error:

> TemplateDoesNotExist at /admin/dashtile/dashtile/80/change/
> colorfield/color.html

This was after I added a color field to a model, then ran `makemigrations` and `migrate`, with that being the only change.  

The field I added: 

    iconBackground = ColorField('iconBackground', default='#000000', blank=True).  

**Expected behavior**
I should be able to view the model in the admin panel.

**Comment by fabiocaccamo** [comment]
@cclloyd have you added `colorfield` to `settings.INSTALLED_APPS` and restarted your app?
