### ISSUE TITLE
Can't set default to None or ''

### ISSUE THREAD

**Issue by selected-pixel-jameson** [fabiocaccamo/django-colorfield#53]
**Python version**
3.6

**Django version**
2.1

**Package version**
0.2.2

**Current behavior (bug description)**
When I set default = None or default = '' the default value is still used. 

**Expected behavior**
I would expect no value to be displayed when this form initially is displayed. Thus forcing the user to enter a value if the field is required or not saving a value at all in the database.

**Comment by selected-pixel-jameson** [comment]
https://github.com/fabiocaccamo/django-colorfield/issues/55

**Comment by fabiocaccamo** [comment]
I think that the default value could be set dynamically based on other attributes, for example:
```python
if kwargs.get('null') == True:
    default = None
elif kwargs.get('blank') == True:
    default = ''
else:
    default = '#FFFFFF'

kwargs.setdefault('default', default)
```

**Comment by fabiocaccamo** [comment]
You can upgrade to `0.3.0` version, remember to run `makemigrations` and `migrate`.
