### ISSUE TITLE
Field is not adding the '#' correctly.

### ISSUE THREAD

**Issue by selected-pixel-jameson** [fabiocaccamo/django-colorfield#54]
**Python version**
3.6

**Django version**
2.1

**Package version**
0.2.2

**Current behavior (bug description)**
When the color field initial loads it is setting the color to a value of 'FFFFFF'. This causes an error to be thrown. Even if I change the color the '#' is still not added to the value. Therefore it's an invalid color. 

**Expected behavior**
I expect it to consider colors without a '#' valid or to add the '#' as needed. 

Strangely enough after I click save and the validation runs a '#' is added to the value and the item will save just fine. 
<img width="1874" alt="Screen Shot 2020-04-02 at 11 22 05 AM" src="https://user-images.githubusercontent.com/28204537/78273244-33d97700-74d4-11ea-8c50-273b9c28a5dd.png">

<img width="1854" alt="Screen Shot 2020-04-02 at 11 20 54 AM" src="https://user-images.githubusercontent.com/28204537/78273168-13112180-74d4-11ea-9da9-4b2095079023.png">

**Comment by fabiocaccamo** [comment]
Are you upgrading from an older version or is this a fresh installation of this package?

**Comment by selected-pixel-jameson** [comment]
I upgraded from 0.2.1 to 0.2.2.

**Comment by fabiocaccamo** [comment]
As you can see in `colorfield/templates/colorfield/color.html` there is a `jscolor` option that forces the `#` prefix and in the field the default value includes the `#`.

I can’t replicate this issue and I have not idea of what could be the cause, have you any idea?

**Comment by selected-pixel-jameson** [comment]
If I install the previous version 0.2.1 this is not a problem. If I install 0.2.2 it is.

**Comment by selected-pixel-jameson** [comment]
I'm guessing it has something to do with the change that we made to the other script.

**Comment by fabiocaccamo** [comment]
It is just the code that make work the inlines executed  on window load event, nothing that could broke the correct behavior.

**Comment by selected-pixel-jameson** [comment]
After diving into this further I'm assuming that you are instantiate the admin form with at least 1 item pre-populated? i.e. Either not setting the 'extra' property or setting 'extra=1', 'extra=2', etc. 

In my scenario I'm setting extra=0. 

Since jscolor is setup when the page loads, and not when the elements are added to the page this causes the issue with it not getting configured correctly because it can't find an input element on the page that has the defined dataset which instantiates the hash:true setting. 

I will continue to work on this, but this is what I'm assuming is happening and why you are not seeing the issue.

**Comment by selected-pixel-jameson** [comment]
Just confirmed. If I set extra=1 I do not see this issue anymore. So.. this is in fact a bug as the scenario of setting extra=0 is definitely a use case.

**Comment by selected-pixel-jameson** [comment]
https://github.com/fabiocaccamo/django-colorfield/pull/55

**Comment by fabiocaccamo** [comment]
Oh nice, that was the problem, yes I had one extra inline by default.
I will test it, merge your PR and release a new version in the next days. Thank you

**Comment by fabiocaccamo** [comment]
You can upgrade to `0.3.0` version, remember to run `makemigrations` and `migrate`.
