### ISSUE TITLE
Colorpicker does not open on custom view, even though it works in admin

### ISSUE THREAD

**Issue by fgebhart** [fabiocaccamo/django-colorfield#56]
**Python version**
3.7.5

**Django version**
3.0.3

**Package version**
0.3.0

**Current behavior (bug description)**
After including a `color_field` in my model like described in the Readme of this repo and after running a collectstatics I am able to pick a color via the colorpicker like expected in the django admin panel. But when including the form field in a custom view and html page like the following, the colorpicker will simply not pop up:
```html
<div class="form-group row">
        <div class="col-sm-2">{{ form.color_field.label }}</div>
        <div class="col-sm-10">{{ form.color_field }}</div>
</div>
```
When using the Firefox inspector I see that my `<div>` field does not have the "event" thing at the end of the line, like it does in the admin panel. So I assume it has something to do static files and the corresponding js files not being able to attach to the relevant input field. Obviously I'm not a js programmer and do not know how to debug this further.

**Expected behavior**
I would like the color picker to show when clicking into the input field in my custom view / html page. Any help is appreciated!

Thanks for your work and this nice tool!

**Comment by fabiocaccamo** [comment]
@fgebhart thank you for reporting this, I will debug it as soon as possible.

**Comment by fgebhart** [comment]
Thanks for your quick response, but I found the missing piece. Thanks to [this stackoverflow post](https://stackoverflow.com/questions/60977056/can-i-add-a-color-picker-to-django-forms):

I simply had to include `{{ form.media }}` inside my `<form>` tag. Works like a charm!

**Comment by almiavicas** [comment]
Thanks for the help! I was struggling with this too

**Comment by ttanvirr** [comment]
Many many thanks. Adding {{ form.media }} before form tag solved my problem of adding a new color. But the color-picker is gone when I want to edit an existing color! Please how to solve this?
