### ISSUE TITLE
z-index issue with Colorpicker and bootstrap dialog

### ISSUE THREAD

**Issue by dadokkio** [fabiocaccamo/django-colorfield#57]
**Python version**
3.8

**Django version**
3.0

**Package version**
0.3.0

**Current behavior (bug description)**
Is not possible to use the colorpicker in bootstrap modal because the z-index of the modal is higher (1050 vs 1000) and the colorpicker stays in background

**Expected behavior**
A way to change the z-index via js or via css

**Comment by fabiocaccamo** [comment]
@dadokkio you have this issue in the admin? 
If not, you could just write some simple css that overrides jscolor `z-index` or bootstrap modal `z-index`.

As you can see [here](https://github.com/fabiocaccamo/django-colorfield/blob/master/colorfield/static/colorfield/jscolor/jscolor.js#L977) `jscolor` supports many css options, feel free to submit a PR to pass custom widget options.

**Comment by dadokkio** [comment]
No, it's on a standard page. This is the result with inspection:

![image](https://user-images.githubusercontent.com/355183/82147675-f8122b00-984f-11ea-9994-a1914046f07b.png)

The css seems to be generated via js and the div has no class. I tried to increase the z-index in jscolor.js but it's overwritten somewhere else so I thought there were a way to set it.

**Comment by fabiocaccamo** [comment]
I understand, the code generated by jscolor by is not fantastic 😅.
Have you the possibility to modify the boostrap z-index instead? 

`jscolor` actually accepts some options passed to the constructor, but this would some rework in the implementation as you can see in the widget js. 

If you want to fix it feel free to submit a PR.

**Comment by dadokkio** [comment]
Yes, the suggestion to modify bootstrap is probably the easiest solution.

In my case, this worked properly:

```
.modal {z-index: 999;}
.modal-backdrop { z-index: 995;}
.sticky-top { z-index: 990;}
```

I've seen that color.js has a similar issue [https://github.com/EastDesire/jscolor/pull/8] and some new commit recently.. let's see if they'll take care of this.

**Comment by fabiocaccamo** [comment]
@dadokkio thank you, your solution could be useful to many others.

There is not any new `jscolor` release, in that case just drop me a line and I will update the library.

**Comment by dadokkio** [comment]
I was talking about this commit:
https://github.com/EastDesire/jscolor/commit/425510ae3ac7d36fc78ceafadb3b43fdf6320866

That should add a class that will permit a css customization.

**Comment by dadokkio** [comment]
Ok, seems that new releases have been finally created

**Comment by fabiocaccamo** [comment]
@dadokkio you can install `0.3.1` version.
