### ISSUE TITLE
Support additional color types

### ISSUE THREAD

**Issue by dyspop** [fabiocaccamo/django-colorfield#58]
**Is your feature request related to a problem? Please describe.**
I'm using ColorField in an HTML builder app. It's really nice but (I think?) it only supports hex colors.

**Describe the solution you'd like**
Add support for RGB, RGBA and HTML-named colors.

**Describe alternatives you've considered**
Alternatively I may couple the ColorField with a custom ColorFieldDisplayType field, with choices like 'hex', 'rgb', 'rgba' and 'html-name' and a translation function. The only real issue here is handling alpha becomes problematic between types.

**Comment by fabiocaccamo** [comment]
@dyspop thank you for this suggestion.
`ColorfField` purpose is to provide a color picker for the django admin using hex-colors. If you need some more advanced color-pickers in the frontend I suggest you to use a more advanced color picker. 

If you make it compatibile with `django-colorfield` feel free to submit a PR keeping in mind that:
- colors must be stored as hex in the database
- any other widget must be optional, it must not replace the current one
- any other javascript color library must be open-source and updated recently

**Comment by fabiocaccamo** [comment]
@dyspop thanks to the great work of @rcatajar the `format` field option is now available. 
Actually the formats supported are `hex` and `hexa`, but it should not be hard to support more color formats.
