### ISSUE TITLE
Transparency picker for Hex code

### ISSUE THREAD

**Issue by ZackPlauche** [fabiocaccamo/django-colorfield#59]
**Is your feature request related to a problem? Please describe.**
The application is missing the ability to add transparency settings to hex code (which is now the additional 2 characters you can add to a hex code).

For example, if you want to have a transparent black color you can now type: #00000050, or for white you can do #FFFFFF50. There's also the short hand extra character #FFF5. A full color would be #FFFF or #FFFFFFFF. A clear color would be #FFF0 or #FFFFFF00.

**Describe the solution you'd like**
I'd like to be able to add 2 additional characters (or do the shorthand version as well of 4 characters) and see a transition option on the color picker.

**Describe alternatives you've considered**
Personally I'm ok with using just a CharField, but that kind of kills the point of having a color picker lol.

**Additional context**
That's really it!

This is how VSCode does it: 
![image](https://user-images.githubusercontent.com/43456955/85204294-2e920880-b31c-11ea-99f1-07b0e78e9ffa.png)

**Comment by fabiocaccamo** [comment]
@ZackPlauche I understand your need, personally I had the same need in the past.

I don't know if the last version of `jscolor` supports the alpha channel, I will check it. Otherwise the only solution would be to support a new color picker fully backward-compatible.

**Comment by fabiocaccamo** [comment]
@ZackPlauche `django-colorfield==0.4.0` supports `format='hexa'` option for doing exactly what you need.
