### ISSUE TITLE
Validation error for colour selected via picker 

### ISSUE THREAD

**Issue by philclaridge** [fabiocaccamo/django-colorfield#61]
**Python version**
3.8

**Django version**
3.0.7

**Package version**
0.3.2 (including jscolor 2.1.1)

**Browser**
Safari and Chrome

**Current behavior (bug description)**
Validation error on admin screen "Enter a valid color."
Occurs for colour edited via picker, or default colour or colour with # previously read from database.
On deeper inspection colours selected with colour picker are displayed without a leading hash symbol. Value without leading hash then fails validation at line 16 of fields.py. (have added additional validator to intercept and confirm value to be validated has no leading hash).

When reading colour from database (that had a leading hash) the colour is now displayed without the leading hash and validation fails on save even if colour not changed. 

Have run collect static to verify have latest JS. 

Have recently upgraded number of other library including upgrade to Django 3.0.7

See image below.

**Expected behaviour**
Unchanged colour and picked colour will not cause validation error.
Leading hash preserved on entered/default colour.

![image](https://user-images.githubusercontent.com/126126/87222806-0885e400-c36f-11ea-9fc5-c58ed5f5658a.png)

**Comment by fabiocaccamo** [comment]
@philclaridge this is really strange. I could understand if your only case would be reading a previously stored color without the `#`, but default colors and colors choosen using the color picker should work fine.

I'm not able to reproduce the issue you reported. In all my tests color is always prefixed correctly by `#`.
Could you try to force delete of browser cache?

**Comment by fabiocaccamo** [comment]
@philclaridge any feedback?

**Comment by fabiocaccamo** [comment]
Feel free to re-open this issue if you have an useful feedback to provide.

**Comment by dryan** [comment]
I believe this is an underlying issue with JSColor when a Content Security Policy doesn't allow `'unsafe-eval'`. I ran into this myself and had to make an exception inside the admin area for my CSP.

**Comment by fabiocaccamo** [comment]
Thank you for the useful information.
