### ISSUE TITLE
Redistributing as MIT with a GPLv3 licensed library?

### ISSUE THREAD

**Issue by biwin** [fabiocaccamo/django-colorfield#62]
JScolor is licensed [GPLv3 ](https://github.com/fabiocaccamo/django-colorfield/blob/master/colorfield/static/colorfield/jscolor/jscolor.js#L5). We are distributing this lib as MIT with GPL code. [JSColor](https://jscolor.com/download/) has clearly stated as

> If you are creating an open source application under a license compatible with the GNU GPL license v3, feel free to use jscolor under the terms of GNU GPL license v3.

Using and distributing this lib as MIT is a violation of GPL.
We have to either release as **GPL** (viral behaviour of GPL) or reconsider the js color picker lib,
Any thoughts on this?

**Comment by isik-kaplan** [comment]
I think this falls under this: [MereAggregation](https://www.gnu.org/licenses/gpl-faq.html#MereAggregation) I think most of the front-end javascript dependencies falls under this.
