### ISSUE TITLE
Background color of the first field does not change

### ISSUE THREAD

**Issue by mhowarth10** [fabiocaccamo/django-colorfield#63]
**Python version**
3.6

**Django version**
3.0.5

**Package version**
0.3.2

**Current behavior (bug description)**
I have 4 color fields. The first one does not change color when I move the slider, but the rest of them do.

![](https://i.imgur.com/sIwcDqt.gif)

Code:

```python
class Test(models.Model):
  test1 = ColorField('Baggrundsfarve', max_length = 7, blank = True)
  test2 = ColorField('Temafarve 1', max_length = 7, blank = True)
  test3 = ColorField('Temafarve 2', max_length = 7, blank = True)
  test4 = ColorField('Tekstfarve', max_length = 7, blank = True, default = '#FFFFFF')
```

**Expected behavior**
Color fields should change background colors when the slider is moved.

**Comment by fabiocaccamo** [comment]
I quickly tested it on an existing project I'm working on (python 3.8 and django 3.1) and I can't replicate this issue.
Could you:
- check if there is any useful log in the browser console
- test it against different python/django versions

**Comment by fabiocaccamo** [comment]
Your model field declaration is the same for all 4 color fields?

**Comment by mhowarth10** [comment]
Sorry, this is my fault. I had the slider on the right handside all the way down to the dark colors.

It works as intended.

Thanks for getting back so quickly.
