### ISSUE TITLE
500 error caused by new palette choice code in 0.4.0

### ISSUE THREAD

**Issue by andrewhayes1979** [fabiocaccamo/django-colorfield#65]
**Python version**
3.8.3

**Django version**
2.2.x

**Package version**
0.4.0

**Current behavior (bug description)**
 - I have a model with ColorFields in it using an older 0.3.2 release of this package
 - just upgraded to 0.4.0
 - new palette choice code in the formfield() method causes a 500 error in the model admin

Essentially, I don't override choices in the model definition, choices weren't a thing in older versions of the package

The choices default to constructing as empty list, []:

When rendering the form-field, your new palette code runs:

```
palette = []
if self.choices is not None:
    choices = self.get_choices(include_blank=False)
    palette = [choice[0] for choice in choices]
```

...since self.choices is [], not None, is calls super get_choices()...

```
        if self.choices:
            choices = list(self.choices)
            if include_blank:
                blank_defined = any(choice in ('', None) for choice, _ in self.flatchoices)
                if not blank_defined:
                    choices = blank_choice + choices
            return choices
        rel_model = self.remote_field.model
```

...since choices is [], it is falsy, the field choices therefore falls through the first if-statement to the lower part of the method that assumes a relational field (e.g. a ForeignKey field)...it tries to do things with self.remote_field

KABLAM! :-D

**Expected behavior**

This should not crash

Recommend you fix by changing the choice-check in Colorfield.formfield() from "if self.choices is not None" to simply "if self.choices", in-line with the underlying Django

**Comment by fabiocaccamo** [comment]
Thank you for reporting this.

@rcatajar could you fix it?

**Comment by fabiocaccamo** [comment]
You can install `0.4.1` version.

**Comment by rcatajar** [comment]
Sorry about that, I was not aware that in older version choices defaults to `[]`. In django 3.0 and above it defaults to `None`

**Comment by fabiocaccamo** [comment]
@rcatajar no problem.
