### ISSUE TITLE
disable colorfield in ModelForm

### ISSUE THREAD

**Issue by nhrnhr0** [fabiocaccamo/django-colorfield#67]
**Python version**
Python 3.9.1

**Django version**
Django==3.1.6

**Package version**
?

**Current behavior (bug description)**
I have this field in models.py:
`backgroundColor = ColorField(default="#ffffff")
`
And in form.py:
```
class MyForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(MyForm, self).__init__(*args, **kwargs)
        self.fields['backgroundColor'].widget.attrs['disabled'] = 'disabled'
```
**Expected behavior**
I want it to disable the color field but the field is still enabled.

**Comment by fabiocaccamo** [comment]
@nhrnhr0 thank you for reporting this, feel free to submit a PR.

**Comment by fabiocaccamo** [comment]
@nhrnhr0 you can upgrade to `0.4.2` version.
