### ISSUE TITLE
Selected color can't be saved because it is not in `COLOR_CHOICES`

### ISSUE THREAD

**Issue by DavidNiceblue** [fabiocaccamo/django-colorfield#68]
I think COLOR_CHOICES will help users quickly choose the color what he want.The colors in COLOR_CHOICES are just recommendation for users.If users want to choose other colors that not in COLOR_CHOICES,I think he can also submit.Otherwise, the COLOR_CHOICES appearing while the color picker exist will be meaningless.

**Comment by fabiocaccamo** [comment]
@DavidNiceblue thank you for reporting this, I think there should be 2 behaviours:

- When color `COLOR_CHOICES` are defined, the picker should display only the choices and allow only a valid choice in validation.

- When `COLOR_SAMPLES` are defined (this property doesn't exist, it should be added), the picker should allow both sample selection or custom color selection.

@rcatajar what do you think about this?

**Comment by rcatajar** [comment]
This is a good idea. 
Unfortunately it seems like jscolor does not have an option to disable the picker, so it's not super easy to implement.

**Comment by fabiocaccamo** [comment]
@rcatajar maybe it is possible to hide the picker spectrum via css, I will try to do it.

**Comment by fabiocaccamo** [comment]
@rcatajar I checked what was possible to do via css, but unfortunately there is just one jscolor instance in each page and it has not any attribute that could allow to select it depending on which input is active.

**Comment by rniem379349** [comment]
@fabiocaccamo thanks for merging my PR, would you consider cutting a new release soon? I could then use this in a project instead of my fork. What do you think?

**Comment by fabiocaccamo** [comment]
@rniem379349 you can upgrade to `0.5.0` version. Thanks for the PR.

**I would keep this issue open until we find a way to hide the spectrum when using `choices`.**
