### ISSUE TITLE
Issue with admin inline and colorfield

### ISSUE THREAD

**Issue by JacobPolloreno** [fabiocaccamo/django-colorfield#7]
The ColorField is initialized with a 'None' value which in turn causes the whole inline model to be required.

**Comment by fabiocaccamo** [comment]
I just released `0.2.0` version, could you check it please?

**Comment by nelsonCastellanos** [comment]
Hi, I have the following issue
Failed lookup for key [class] in {'default': '# 000000', 'maxlength': '18', 'id': 'id_color_texto_informacion'}

This appears on the line on the line:
  class = "form-control colorfield_field jscolor {{widget.attrs.class}}"
archive:
color.html

**Comment by fabiocaccamo** [comment]
@nelsonCastellanos which python and django versions are you using?

**Comment by nelsonCastellanos** [comment]
I am using the version 3.6.7

**Comment by fabiocaccamo** [comment]
@nelsonCastellanos I need more informations to debug the problem:
-   Python version: 3.6.7
-   Django version: ?
-   colorfield version: ?
-   when is raised this error? In the admin changelist page? In the admin object page? Using a form?

**Comment by nelsonCastellanos** [comment]
- Django==2.2.5
- django-colorfield==0.2.0

The error arises when when I generate a function of type StackedInline
Example: 
ModelAdmin(ImportExportModelAdmin, NonSortableParentAdmin):
      inlines = [
      ]
ModelInline(admin.StackedInline):
   model = Model 
   extra = 0

And I try to add a new record of the inlline model

**Comment by fabiocaccamo** [comment]
@nelsonCastellanoscould you try to install `0.2.1` version? (remember to run `python manage.py collectstatic` after updating the package).

**Comment by nelsonCastellanos** [comment]
thanks!

**Comment by nelsonCastellanos** [comment]
Hi,
I had problems with ModelInline when adding a new model.
you can add $ (document) .ready () function to colorfield.js file

**Comment by nelsonCastellanos** [comment]
Hi. I am problem with colorfield.js when django.jQuey is undefined

**Comment by nelsonCastellanos** [comment]
can you use:
  $(document).ready(function(){
	
  })

**Comment by fabiocaccamo** [comment]
Hi @nelsonCastellanos, please open a new issue using the bug template could trying to be more specific about your problem.
