### ISSUE TITLE
Options not working when not using palette (choices/samples)

### ISSUE THREAD

**Issue by jan-szejko-steelseries** [fabiocaccamo/django-colorfield#80]
**Python version**
2.7

**Django version**
1.11

**Package version**
0.7.1

**Current behavior (bug description)**
When the palette options are not used, the input renders with the `data-jscolor` attribute ending with `...,palette:}`. It causes the options to be ignored, e.g. a non-required field becomes required.

**Expected behavior**
An empty palette should not cause other options to be ignored.

**Comment by fabiocaccamo** [comment]
@jan-szejko-steelseries thank you for reporting this, could you show your field implementation (in your model)?

**Comment by jan-szejko-steelseries** [comment]
> @jan-szejko-steelseries thank you for reporting this, could you show your field implementation (in your model)?

```python
from colorfield.widgets import ColorWidget
from colorfield.fields import ColorField
from django.template import loader
from django.utils.safestring import mark_safe


class ColorPickerWidget(ColorWidget):
    def render(self, name, value, attrs=None):
        context = self.get_context(name, value)
        template = loader.get_template(self.template_name).render(context)
        return mark_safe(template)


class ColorPickerField(ColorField):
    def formfield(self, **kwargs):
        kwargs['widget'] = ColorPickerWidget()
        return super(ColorField, self).formfield(**kwargs)
```

**Comment by jan-szejko-steelseries** [comment]
@fabiocaccamo  You can experiment on https://jscolor.com/examples/ to see that an input with `data-jscolor="{required:false,palette:}"` does not allow an empty value.

**Comment by fabiocaccamo** [comment]
@jan-szejko-steelseries you can upgrade to `0.7.2` version. Thank you for the PR.
