### ISSUE TITLE
Update README to link to JSColor license

### ISSUE THREAD

**Issue by StevenMapes** [fabiocaccamo/django-colorfield#82]
JSColor is only GNU GPL v3 for open source, GNU GPL v3 compatible, licenses. For anything else it requires a paid commercial license. 
https://jscolor.com/download/

<a href="https://dashboard.polar.sh/fabiocaccamo/django-colorfield/issues/82">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://dashboard.polar.sh/api/github/fabiocaccamo/django-colorfield/issues/82/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://dashboard.polar.sh/api/github/fabiocaccamo/django-colorfield/issues/82/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@StevenMapes I'm aware of this limitation, unfortunately at the moment I have not the time for working on it. 

I created this discussion #83.

**Comment by fabiocaccamo** [comment]
For anyone interested in dealing with this problem, a PR for #168 would be much appreciated!
